### ISSUE TITLE
react-native?

### ISSUE THREAD

**Issue by victorbadila** [gamell/fetch-base64#6]
I presume this isn't exactly an issue as it is not stated that it should work with react native, but I just tried it and it seems I am having problems loading the module. Should the description contain the fact that it was not made for react-native and that it might not work there?

**Comment by gamell** [comment]
Hi Victor, thanks for the heads up. As you say, that actually doesn't seem to be an issue with this package. This is a **node** module, and you should be able to use it with anything that implements or uses core nodejs standard API and libraries (like `url`, `path`, etc.).

I just tested the package with the latest version of nodejs and it works. If you can dig deeper and tell me why it is exactly not working on react native I can definitely add a warning or disclaimer.

Thank you!

**Comment by victorbadila** [comment]
Hi, I added the module to a react-native project, it builds well but when running (iOS for example) I get an error when I want to import the module:

```
Unable to resolve module 'path' from '<project dir...>/node_modules/fetch-base64/node_modules/mime-types/index.js': Module does not exist in the module map
```
Hope this helps :)

**Comment by gamell** [comment]
Hi Victor,

Thanks for getting back on this so quickly. So, yes, as I said, it seems that the `fetch-base64` module is unable to load the core nodejs module `path` which deals with files and pathnames. I am not sure if that is expected or it might be due to some misconfiguration on your project. Sorry, but I have never used react native myself.

**Comment by victorbadila** [comment]
Hi Joan and thanks as well for getting back. There is no react native `path` native module, the runtime on the mobile devices are different from node/v8 as far as I know, so I guess it wasn't supposed to work from the beginning. It seems there already was a popular library for my needs and I ended up using that. Cheers!

**Comment by gamell** [comment]
Glad you figured it out @victorbadila . Cheers!
