### ISSUE TITLE
Adding support for custom headers sent to http request

### ISSUE THREAD

**Issue by ivnnv** [gamell/fetch-base64#7]
Hi, first of all, thanks for sharing the package.

https://github.com/gamell/fetch-base64/blob/a3751249de21489485850fed3adb6506b70bffad/lib/fetch-remote.js#L20

Would it be possible to add custom header parameters to the request? For example i think im having some issues with cache so adding any of the no-cache headers would be useful.
Ill try to make a PR if i continue having issues with recurrent calls to same url which has changed several times in few minutes.

**Comment by gamell** [comment]
Hey Ivan, sorry I've been busy with other things, but I'll try to make some time to look into this soon. It seems definitely doable.

**Comment by gamell** [comment]
Available in [v2.1.1](https://www.npmjs.com/package/fetch-base64/v/2.1.1)
